# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leJOkIhXUiBM_xkr58BYfjiOYLLAbC9F
"""

from google.colab import files
import pandas as pd
files.upload()

# 1) Load the CSV file into a DataFrame
df = pd.read_csv("housing.csv")

df.head()



print("Column Information:")
print(df.info())

print("\nStatistical Summary of Numerical Columns:")
print(df.describe())

df['ocean_proximity'].value_counts()

print("\nColumns with missing values:")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])





